parameters:
    okvpn_fixture.table: 'okvpn_fixture_data'
    okvpn_fixture.path_data_main: 'Migrations/Data/ORM'
    okvpn_fixture.path_data_demo: 'Migrations/Data/Demo/ORM'

services:
    okvpn_fixture.data.executor:
        class: Okvpn\Bundle\FixtureBundle\Migration\DataFixturesExecutor
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'

    okvpn_fixture.data.loader:
        class: Okvpn\Bundle\FixtureBundle\Migration\Loader\DataFixturesLoader
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@service_container'

    okvpn_fixture.listener.configuration_resolver:
        class: Okvpn\Bundle\FixtureBundle\EventListener\ConfigurationResolver
        arguments: ['%okvpn_fixture.table%']
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    okvpn_fixture.command.load_data_fixtures:
        class: Okvpn\Bundle\FixtureBundle\Command\LoadDataFixturesCommand
        arguments:
            - '@doctrine'
            - '@okvpn_fixture.data.loader'
            - '@okvpn_fixture.data.executor'
            - '@parameter_bag'
        tags:
            - { name: console.command }
